{% set version = "2020.3.1" %}
{% set buildnumber = 0 %}

package:
  name: daal4py
  version: {{ version }}

source:
  url: https://github.com/IntelPython/daal4py/archive/{{ version }}.tar.gz
  sha256: 5007a706b40242f6f31d5a3bea5a2f38553f1325416df80e38e9c61ac974acf4
build:
  number: {{ buildnumber }}
  include_recipe: false

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - numpy
    - daal-devel >=2020.3
    - cython
    - jinja2
    - mpich  # [not win]
    - clang-tools
  run:
    - python
    - daal >=2020.3
    - {{ pin_compatible('numpy') }}

test:
  requires:
    - pandas
    - scipy
    - scikit-learn
    - xgboost  # [not win and py<=38]
    - lightgbm  # [not win and not osx]
    - pytest
    - mpich  # [not win]
  source_files:
    - examples
    - tests
    - daal4py
  commands:
    - python -c "import daal4py"
    - mpirun -n 4 python -m unittest discover -v -s tests -p spmd*.py  # [not win]
    - python -m unittest discover -v -s tests -p test*.py
    - pytest --pyargs daal4py/sklearn/
    - python examples/run_examples.py
    - python -m daal4py examples/sycl/sklearn_sycl.py

about:
  home: https://intelpython.github.io/daal4py/
  license: Apache-2.0
  license_file:
    - LICENSE
    - doc/third-party-programs.txt
  summary: A convenient Python API to Intel (R) oneAPI Data Analytics Library
  description: |
    <strong>LEGAL NOTICE: Use of this software package is subject to the
    software license agreement (as set forth above, in the license section of
    the installed Conda package and/or the README file) and all notices,
    disclaimers or license terms for third party or open source software
    included in or with the software.</strong>
    <br/><br/>
    EULA: <a href="https://opensource.org/licenses/Apache-2.0" target="_blank">Apache-2.0</a>
    <br/><br/>
  dev_url: https://github.com/IntelPython/daal4py
  doc_url: https://intelpython.github.io/daal4py

extra:
  recipe-maintainers:
        # GitHub IDs for maintainers of the recipe.
    - napetrov
    - PetrovKP
    - SmirnovEgorRu
